################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: v1
kind: Secret
metadata:
  name: oidc-client-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/oidc/{{ .Values.auth.oidc.issuer }}/{{ .Values.auth.oidc.client }}"
type: Opaque
stringData:
  {{ if .Values.auth.secrets.oidc-client-secret }}
  AUTH_OIDC_CLIENT_SECRET: "{{ .Values.auth.secrets.oidc-client-secret }}"
  {{ else }}
  AUTH_OIDC_CLIENT_SECRET: "<client-secret>"
  {{ end }}
