################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: v1
kind: Secret
metadata:
  name: root-ca
  annotations:
    avp.kubernetes.io/path: "kv/data/certificates"
stringData:
  {{ if .Values.auth.secrets.ca-domain }}
  AUTH_OIDC_CLIENT_SECRET: "{{ .Values.auth.secrets.ca-domain }}"
  {{ else }}
  ca.crt: "<root-ca.crt>"
  {{ end }}
