################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

{{- if .Values.auth.withRootCa }}
apiVersion: v1
kind: Secret
metadata:
  name: root-ca
  annotations:
    avp.kubernetes.io/path: "kv/data/certificates"
stringData:
  ca.pem: "<root-ca.crt>"
{{- end }}
